### PR TITLE
Return error when compiling unsatisfiable regexes

### LINKED ISSUE #11: Unsatisfiable regexes cause panics
Currently, when trying to sample an unsatisfiable regex, `rand_regex` panics.

You can use the example cli program to reproduce this easily:

```
$ cargo run --example cli -- '[a&&b]'

thread 'main' panicked at src/lib.rs:815:49:
cases not empty: EmptyRange
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Panicking isn't really an option for my use-case, as I'm in an environment that can't use `catch_unwind`.
Would it be possible get  `rand_regex::Regex::Compile`, to return an `Err`, when a regex is unsatisfiable?

### PR DESCRIPTION
**Pull request by 414owen**
Closes https://github.com/kennytm/rand_regex/issues/11

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -103,11 +103,15 @@ pub enum Error {
     /// });
     /// ```
     Syntax(Box<regex_syntax::Error>),
+
+    /// Example of an unsatisfiable regex: `[a&&b]`
```
Comment (kennytm) [inline src/lib.rs]:
``````suggestion
    /// The regex can never be matched, and thus it is impossible to generate 
    /// any samples from the regex.
    ///
    /// # Examples
    ///
    /// ```
    /// let err = rand_regex::Regex::compile(r"[a&&b]", 100).unwrap_err();
    /// assert_eq!(err, rand_regex::Error::Unsatisfiable);
    /// ```
``````

File: src/lib.rs [hunk 2]
```diff
@@ -450,8 +455,8 @@ impl Regex {
             HirKind::Capture(hir::Capture { sub, .. }) => Self::with_hir(*sub, max_repeat),
 
             HirKind::Literal(hir::Literal(bytes)) => Ok(Self::with_bytes_literal(bytes.into())),
-            HirKind::Class(hir::Class::Unicode(class)) => Ok(Self::with_unicode_class(&class)),
-            HirKind::Class(hir::Class::Bytes(class)) => Ok(Self::with_byte_class(&class)),
+            HirKind::Class(hir::Class::Unicode(class)) => Ok(Self::with_unicode_class(&class)?),
+            HirKind::Class(hir::Class::Bytes(class)) => Ok(Self::with_byte_class(&class)?),
```
Comment (kennytm) [inline src/lib.rs]:
```suggestion
            HirKind::Class(hir::Class::Unicode(class)) => Self::with_unicode_class(&class),
            HirKind::Class(hir::Class::Bytes(class)) => Self::with_byte_class(&class),
```

File: src/lib.rs [hunk 3]
```diff
@@ -507,10 +512,11 @@ impl Regex {
...
             regex.compiled.repeat_const *= upper;
         } else {
-            regex
-                .compiled
-                .repeat_ranges
-                .push(Uniform::new_inclusive(lower, upper).expect("upper >= lower"));
+            regex.compiled.repeat_ranges.push(
+                Uniform::new_inclusive(lower, upper)
+                    .ok()
+                    .ok_or(Error::Unsatisfiable)?,
```
Comment (kennytm) [inline src/lib.rs]:
```suggestion
                    .map_err(|_| Error::Unsatisfiable)?,
```

File: src/lib.rs [hunk 4]
```diff
@@ -602,7 +608,9 @@ impl Regex {
         }
         Ok(Self {
             compiled: Kind::Any {
-                index: Uniform::new(0, choices.len()).expect("choices not empty"),
+                index: Uniform::new(0, choices.len())
+                    .ok()
+                    .ok_or(Error::Unsatisfiable)?,
```
Comment (kennytm) [inline src/lib.rs]:
```suggestion
                    .map_err(|_| Error::Unsatisfiable)?,
```

File: src/lib.rs [hunk 5]
```diff
@@ -778,10 +786,12 @@ fn compile_unicode_class(ranges: &[hir::ClassUnicodeRange]) -> Kind {
     });
 
     if normalized_len as usize > SHORT_UNICODE_CLASS_COUNT {
-        return Kind::LongUnicodeClass(LongUnicodeClass {
-            searcher: Uniform::new(0, normalized_len).expect("normalized_len > 0"),
+        return Ok(Kind::LongUnicodeClass(LongUnicodeClass {
+            searcher: Uniform::new(0, normalized_len)
+                .ok()
+                .ok_or(Error::Unsatisfiable)?,
```
Comment (kennytm) [inline src/lib.rs]:
```suggestion
                .map_err(|_| Error::Unsatisfiable)?,
```

File: src/lib.rs [hunk 6]
```diff
@@ -792,10 +802,12 @@ fn compile_unicode_class(ranges: &[hir::ClassUnicodeRange]) -> Kind {
         }
     });
 
-    Kind::ShortUnicodeClass(ShortUnicodeClass {
-        index: Uniform::new(0, cases.len()).expect("cases not empty"),
+    Ok(Kind::ShortUnicodeClass(ShortUnicodeClass {
+        index: Uniform::new(0, cases.len())
+            .ok()
+            .ok_or(Error::Unsatisfiable)?,
```
Comment (kennytm) [inline src/lib.rs]:
```suggestion
            .map_err(|_| Error::Unsatisfiable)?,
```

File: src/lib.rs [hunk 7]
```diff
@@ -806,15 +818,17 @@ struct ByteClass {
...
         let mut cases = Vec::with_capacity(256);
         for range in ranges {
             cases.extend(range.start()..=range.end());
         }
-        Self {
-            index: Uniform::new(0, cases.len()).expect("cases not empty"),
+        Ok(Self {
+            index: Uniform::new(0, cases.len())
+                .ok()
+                .ok_or(Error::Unsatisfiable)?,
```
Comment (kennytm) [inline src/lib.rs]:
```suggestion
                .map_err(|_| Error::Unsatisfiable)?,
```

File: src/lib.rs (hunk 3 above)
Comment (414owen) [reply src/lib.rs]: This is very much just a matter of taste, unless you think that the compiler will produce different results?

It's your repo, so of course I'll make the change, but this was the way I wrote it intentionally.

Comment (kennytm) [reply src/lib.rs]: @414owen  The `.ok().ok_or()` route only works for these context-less errors, like the current `Error::Unsatisfiable`. If we wish to incorporate details about the original error into the new error you must use `.map_err()`, calling `.ok()` will make the original error unavailable.

**Comment by kennytm** [comment]
Thanks, this is now available as v0.18.1.
